### ISSUE TITLE
Support for selectors

### ISSUE THREAD

**Issue by EtienneBruines** [napsy/go-css-parser#3]
Even when not being able to 'understand' those selectors, it now throws an invalid syntax error.

These three are examples (test cases) that currently do not pass a simple `Unmarshal`. 
```go
ex6 := `.rule {
		style1: value1;
		style2: value2;
}`

ex7 := `#rule {
		style1: value1;
		style2: value2;
}`

ex8 := `#navbar div .red {
		style1: value1;
		style2: value2;
}`
```

**Comment by napsy** [comment]
The parser in latest ``master`` now detects and parses styles with . and # selectors but isn't able to understand them. So the first two examples you gave will now pass.

**Comment by napsy** [comment]
The third example also passes, closing.

**Comment by EtienneBruines** [comment]
That is amazing, @napsy  - Thank you :-)
